jobs:
  - job: Ubuntu_Build
    pool:
     vmImage: 'ubuntu-latest'

    steps:
     - task: NodeTool@0
       inputs:
        versionSpec: '10.x'
       displayName: 'Install Node.js'

     - script: |
        npm run eslint 
       displayName: 'Linting'

     - script: |
        npm install
        npm link 
       displayName: 'Install and Link'

     - script: |
          taiko-selenoid
       displayName: 'Setup Selenoid'
     - script: |
        npm test
       displayName: 'Run Test'