pool:
   vmImage: 'macos-10.15'
  
stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

- stage: install
  displayName: Install and Run Test
  jobs:
  - job: Install
    steps:
      - task: Npm@0
        inputs:
         command: install
        displayName: 'npm install'
      - task: Npm@0
        inputs:
         command: link
        displayName: 'npm link'
        
      - script: |
          taiko-selenoid
        displayName: Install Selenoid Dependencies
      - task: Npm@0
        inputs:
          command: test
        displayName: Run Selenoid Test