pool:
   vmImage: 'macos-10.15'
  
stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

- stage: install
  displayName: Npm Install and link
  jobs:
  - job: Install
    steps:
      - task: Npm@0
        inputs:
         command: install
        displayName: 'npm install'
      - task: Npm@0
        inputs:
         command: link
        displayName: 'npm link'

- stage: CLI
  displayName: Taiko Selenoid CLI
  jobs:
  - job: Install
    steps:  
      - script: |
          export PATH="$HOME/.node/bin:$PATH"
          /usr/local/lib/node_modules/taiko-selenoid
        displayName: 'Install Selenoid'