pool:
   name: Default
   vmImage: 'macos-10.15'
  
stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        inputs:
          command: install
        displayName: 'npm install and build'
      
      - task: Npm@1
        inputs:
          command: custom
          customCommand: link
        displayName: 'npm link'